# Generated by Django 5.2.11 on 2026-05-15 13:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry_table',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
