# Generated by Django 5.2.11 on 2026-05-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_enquiry_table_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(max_length=200),
        ),
    ]
